service: images-nicholasgriffin-dev

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  timeout: 10
  region: eu-west-1

functions:
  resize:
    handler: index.resize
    events:
      - http:
          path: resize
          method: get
          cors: true
