service: images-nicholasgriffin-dev

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - 'serverless-apigw-binary'

custom:
  apigwBinary:
    types:
      - '*/*'

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  timeout: 10
  region: eu-west-1

functions:
  api:
    handler: server.express
    events:
      - http: ANY {proxy+}
      - http: ANY /
